Add support for container tabs
hackademix/noscript pull request #218
Opened 2021-11-06 23:16 UTC by aaronkollasch

This is a work in progress for supporting Firefox containers (#5, #166).

- Adds separate policies for each new container. Container policies are empty by default.
- The current tab's container permissions can be edited from the NoScript popup. All containers are editable in the "NoScript Options" page. Exporting and importing are supported.
- Adds a [ContextStore](https://github.com/aaronkollasch/nscl/blob/container-tabs/common/ContextStore.js) in nscl to store policies for each container. 
- No changes to the filtering backend except to make  `src/bg/RequestGuard.js` use the correct policy for each request.

2021-11-07 10:56 UTC, jtotht commented
> Container policies are empty by default.

Does this mean that if I have set a site trusted, it won’t be trusted anymore in containers? While being able to configure different policies per container is a nice feature, I think in most cases if one trusts a site, and then it trusts it in all containers, the containerless policies should continue to apply in containers unless specifically overridden.

2021-11-07 15:56 UTC, aaronkollasch commented
Thanks, you make a good point. The reason why I had it that way is that the default permissions list is quite long, and it can be laborious to clear the list for every container if desired. (Some users' containers can number in the 10's or more)

Using the containerless policy is the better default, true. Perhaps I could add a "clear" button to the Per-site Permissions tab, which clears the selected container's rules (after a confirmation prompt).

2021-11-07 17:12 UTC, aaronkollasch commented
Just added a commit on default container policies. Whenever a new container is created, it will now take on the policies of the default container. However, changes made to any container's policy will not propagate to other containers. I think that is a good balance.

Note that this is more permissive than plugins like [Cookie AutoDelete](https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/) which default to blocking everything for each new container. Since NoScript has a default allowlist, I suppose it makes sense to propagate it to new containers, but it could be unexpected behavior for some users.

2021-11-13 21:46 UTC, jtotht commented
> The reason why I had it that way is that the default permissions list is quite long, and it can be laborious to clear the list for every container if desired.

> Just added a commit on default container policies. Whenever a new container is created, it will now take on the policies of the default container. However, changes made to any container's policy will not propagate to other containers. I think that is a good balance.

It can be laborious the other way round as well: I have for example half a dozen containers for Google stuff, and Google has quite some domains (*.google.com, gstatic.com, googlevideo.com, youtube.com, blogger.com etc., let alone country-specific domains like google.co.uk). If Google decides to load things from yet another domain, say alphabet.com, I have to go through each container to add it. If I trust Google won’t load viruses in container A, it won’t load them in container B either.

2021-11-13 22:30 UTC, aaronkollasch commented
Yeah it can get laborious. Right now the best way to copy configs across containers is to edit the ContextStore json from the debug menu.

I could imagine defining a set of profiles ("Google", etc.) and assigning containers (firefox-container-1, firefox-container-2, etc.) to different profiles. However, this seems needlessly complicated.

Probably a better way is to add a "copy profile from..." dropdown in the options that copies the profile from a selected container. Would that work for you?

There is the question of what to copy – ideally it would append/update rather than replace the current profile's settings, but this makes things tricky in terms of managing conflicts. Perhaps it should merge the site list and replace all other settings.

2021-11-18 01:39 UTC, aaronkollasch commented
I added a selector in options.js to copy another container's profile to the currently viewed container. The new profile just replaces the current profile right now. It's possible to have the site lists merge/update, but that could be needless complexity.

There is another issue with the settings: each container has a separate Policy instance and thus its own preset customizations. I don't think there's a need to have different presets for each container, so ideally the containers should mirror the default container's presets. I just need to find a good way to make that happen.

2021-12-02 16:29 UTC, aaronkollasch commented
I reverted commit https://github.com/aaronkollasch/noscript/commit/8d8bb4c0a2047529d99a2725cbfc739858e63f14 which switched `ns.computeChildPolicy()` to get the tab's `cookieStoreId` from the TabCache, allowing a browser API call to be removed from `RequestGuard.injectPolicyScript()`.

This caused reliability issues as the TabCache didn't always have the `tabId` in question, so `ns.computeChildPolicy()` would use the default policy instead of the container's policy. I'd like to use the TabCache but only if I can get it to work reliably.

Perhaps I could add a TabCache update or `browser.tabs.get(tabId)` fallback if `tabId` is not in the TabCache. This would require `ns.computeChildPolicy()` to be an async function, though.

2021-12-06 18:21 UTC, aaronkollasch commented
Instead of getting the `cookieStoreId` from the TabCache or `browser.tabs.get`, it is now passed from `nscl/ service/DocStartInjection.js`.

2021-12-11 07:54 UTC, aaronkollasch commented
I've covered the features I can think of, so I'm going to mark this as ready for review.

Some to-do's remaining are:
- Add internationalization:
  - Button labels in `ui/options.html`: 
    - `lbl-containers`
    - `select-container-label`
    - `copy-container-label`
    - `btn-clear-container`
  - The name of the default container ("Default"):
    - in `ui/popup.html` `container-id`
    - in `ui/popup.js`
    - in `ui/options.html` `select-container` and `copy-container`
    - in `ui/options.js:updateContainerOptions()`
  - The alert message for `ui/options.js:copyContainer()` 
  - The alert message for `#btn-clear-container`
- Revert `.gitmodules` after merging nscl

Also, as @jtotht mentioned [earlier](https://github.com/hackademix/noscript/issues/5#issuecomment-752244068), adding the `contextualIdentities` permission enables the Container Tabs feature for all installs, even for users who don't turn on container tab support. This is not ideal, but I think the cost is small if the feature isn't used.

I've been daily driving NoScript with these changes for about a month now, and can say I've found container-specific permissions really useful, as there are a bunch of sites I use but don't want to allow everywhere. So I now find myself reflexively clicking the disable restrictions button less often :)

2022-04-06 06:59 UTC, aaronkollasch commented
Just rebased on main – I merged all commits to make rebasing easier. The original pull request's commit history, based on [11.2.12rc3](https://github.com/hackademix/noscript/releases/tag/11.2.12rc3) (4cfdebdeacf386b04a900a33953c92e75afed58d), is now saved in a separate branch: [container-tabs-original](https://github.com/aaronkollasch/noscript/tree/container-tabs-original) and its [nscl submodule](https://github.com/aaronkollasch/nscl/tree/container-tabs-original).

2022-05-03 12:40 UTC, craigcomstock commented
@aaronkollasch just tried this and so far a simple test seems to do what I was looking for: trust domains per container. Sweet! Let me know if I can help with testing or development.

2023-03-15 13:00 UTC, Hoeze commented
Can this be merged?

2024-01-28 10:44 UTC, kgkgn commented
Any chance we can maybe push this to be reviewed for potential merging? Been following this PR for a while and would love to see it gets merged as I use both container tabs and noscript fairly heavily, and would love to see them working together ;)))

Anything I can do?

2024-02-07 14:35 UTC, craigcomstock commented
I switched to a multi-instance multi-profile method of working. Made a script to manage it, save cookies in my dotfiles git repo ($HOME/.gitignore = '*'). Been working pretty good. :) Easily shared between linux and macos at least.

```
if [ "$1" = "-l" ]; then
  ls $HOME/website
  exit 0
fi
if [ "$1" = "-s" ]; then # save
  cd $HOME
  for d in $HOME/website/*; do
    git add -f $d/cookies.sqlite
  done
  cd -
  exit 0
fi
if command -v firefox; then
  ff=$(which firefox)
elif command -v firefox-esr; then
  ff=firefox-esr
else
  ff=/Applications/Firefox.app/Contents/MacOS/firefox
fi
# redacted use of pass command to find the password for the site :)
$ff --profile $HOME/website/$1 https://$1  &
```

2025-11-07 08:09 UTC, GRBurst commented
Any news on this @hackademix @aaronkollasch, what are the blockers here?
- Can we put `contextualIdentities` behind a setting, so it is only queried and enables the Container Feature when the setting like `Enable Container Support` or similar is enabled (in case that is a blocker)?

2025-11-09 15:42 UTC, aaronkollasch commented
@GRBurst I don't think it's possible to place `contextualIdentities` behind a setting, so either a separate noscript would have to be released, or it would have to be enabled for all users. Haven't heard anything from @hackademix re this PR, though.

2026-04-08 05:31 UTC, hackademix commented
Hey, thank you very much for this great work, and sorry for not getting at you earlier.

I've looked at the last revision,  I'm very impressed and I'd like to merge this feature ASAP.

I've got some questions, though:

1. Would the `contextualIdentities` permission cause existent users to get the "new permission" prompt and possibly accidentally keep NoScript disabled if they ignore or don't understand it?
2. If that is the case, would it be acceptable for you if we merged the source code but at build time we created a separate package with the permission enabled and a separate update path (like we do for the Tor-hosted versions), and would you modify the code so that if the permission is not available it gracefully degrades keeping the feature hidden and neutral?
3. In case we go on and merge, either in "regular" NoScript (if the extra permission is not an issue) or as a separate version/package, could you please make all the user-facing messages localizable?

Thanks again!

2026-04-08 06:54 UTC, aaronkollasch commented
Thanks for getting back, I'm glad to hear you'd like to merge the feature!

1. I don't think there is a "new permission" prompt for the `contextualIdentities` permission. However, installing a plugin with that permission automatically enables the container tabs feature, which changes some aspects of Firefox (for example, right clicking the + tab button shows a list of container tabs). I don't have an issue with this, but some users might.
2. That would work for me. The code should already be compatible with `contextualIdentities` being disabled. It works by replacing `ns.policy` with `ns.getPolicy(cookieStoreId)`, and looking up `cookieStoreId` in `ns.contextStore` with `ns.policy` as a fallback. If `contextualIdentities` is disabled, `tab.cookieStoreId` and `request.cookieStoreId` are both nil, and `ns.getPolicy(cookieStoreId)` just returns `ns.policy`. I've tested this in Firefox and pre-MV3 Chrome. One thing I might change is, I've hidden the option "Enable support for container tabs" in Chrome, but I should probably do the same in Firefox if `contextualIdentities` is not enabled.
3. Sure thing! Would that entail putting the hardcoded strings into `src/_locales/*/messages.json`? Not confident in translating to all those languages :)

2026-04-08 07:39 UTC, hackademix commented
> Would that entail putting the hardcoded strings into src/_locales/*/messages.json?

No, you just need to do it for English. A fine pool of Weblate localizators would translate in the other languages after the merge.

2026-04-10 02:37 UTC, aaronkollasch commented
I just updated the branch to make user-facing messages localizable. I also fixed a few issues I found, mostly regarding incorrect uses of the default policy rather than the container's policy in code added after the original PR.

I also removed the `container-tabs` portion of `.gitmodules` so the nscl change shows up as a merge conflict. Should I submit a PR for the nscl changes to that repo first?

edit: submitted PR at https://github.com/hackademix/nscl/pull/11

2026-04-11 07:55 UTC, hackademix commented on src/ui/ui.js
> +        await this.updateSettings({policy, contextStore, reloadAffected});
Is this line intentional? Doesn't it throw?

2026-04-11 08:11 UTC, hackademix requested changes

2026-04-11 08:11 UTC, hackademix commented on src/ui/ui.js
> +        debug("id", cookieStoreId, "has cookiestore", currentPolicy);
```suggestion
        debug("id", cookieStoreId, "has cookiestore", currentPolicy); // DEV_ONLY
```

2026-04-11 08:11 UTC, hackademix commented on src/ui/ui.js
> +        debug("default cookiestore", cookieStoreId);
```suggestion
        debug("default cookiestore", cookieStoreId); // DEV_ONLY
```

2026-04-11 08:11 UTC, hackademix commented on src/ui/ui.js
> +      let currentSnapshot = this.policy.snapshot+this.contextStore.snapshot;
```suggestion
      const currentSnapshot = `${this.policy.snapshot}${this.contextStore.snapshot}`;
```

2026-04-11 08:11 UTC, hackademix commented on src/ui/ui.js
> +            UI.snapshot = UI.policy.snapshot+UI.contextStore.snapshot;
```suggestion
            UI.snapshot = `${UI.policy.snapshot}${UI.contextStore.snapshot}`;
```

2026-04-11 17:15 UTC, aaronkollasch commented on src/ui/ui.js
> +        await this.updateSettings({policy, contextStore, reloadAffected});
This looks like a rebasing error.
`await this.updateSettings({policy, contextStore, reloadAffected});` corresponds to an old version of noscript and should have been replaced by the other line, `await this.updateSettings({policy: this.policy, contextStore: this.contextStore, reloadAffected});`

2026-04-11 17:18 UTC, aaronkollasch commented on src/ui/ui.js
> +        await this.updateSettings({policy, contextStore, reloadAffected});
```suggestion
```

2026-04-11 17:30 UTC, aaronkollasch commented on src/ui/ui.js
@hackademix Not related to this PR, but this should be
```suggestion
        settingsListeners.delete(l);
```

2026-04-12 04:26 UTC, aaronkollasch commented
Thanks for the suggestions!

Also, if you'd like an example of how other extensions deal with container tabs, [Cookie-AutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) is one popular extension that includes `contextualIdentities` in its manifest in order to support container tabs:
https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/blob/d9e01ba4acfeee7d49ef8edcc9a64b53d3fa568e/extension/manifest.json#L44

2026-04-12 09:17 UTC, hackademix commented on src/ui/ui.js
Good catch! So lucky it's never called (so far) 😅

2026-04-12 09:22 UTC, merged